
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttt3
    password:
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
